let defCompl = [
    "[user] I love your hairstyle!",
    "[user] you look lovely as ever!",
    "[user] I'm really glad I met you!",
    "Hey everyone, have you met this swell person [user] yet?",
    "[user] always brightens my day!",
    "I bet [user] is so magical that (s)he sweats glitter!",
    "[user] has **the cutest** elbows I've ever seen!",
    "[user] is more fun than bubble wrap!",
    "[user] is my reason to smile!",
    "Any team would be lucky to have [user] in it!",
    "This server is so much better with [user] in it!",
    "Everytime [user] talks to me, I start to blush...",
    "[user] has really nice long arms!",
    "People blush when they see [user] walking down the street.",
    "I as a robot may be technically perfect, but [user] sure is something else!",
    "Being around [user] is like a happy little vacation.",
    "It turns out [user] is one of the smartest people around!",
    "Who raised [user]? They deserve a medal for a job well done.",
    "How does [user] keep being so funny and making everyone laugh?",
    "Colors seem brighter when [user] is around!",
    "Around [user], I’m the best possible version of myself.",
    "Whenever [user] and I are together, everything seems possible.",
    "Loving [user] feels like the most natural thing.",
    "I didn’t know how important friendship was until I met [user].",
    "Hugging [user] is the only comfort I need.",
    "The very idea of [user] makes me smile inside!",
    "Whenever I have a tough day, I remember [user] and it gives me strength and hope.",
    "[user] is awesomeness personified.",
    "Thank you [user]. Thank you for everything!",
    "I think [user] would make a really great parent someday!"
];

module.exports = defCompl;