var defJokes = [
    "If you spent your day in a well, can you say your day was well-spent?",
    "I Googled \"how to start a wildfire\". I got 48,500 matches.",
    "What do snowmen do in their spare time? Not much, just chilling.",
    "What do you say to a hitch-hiker with just one leg? Hop in!",
    "Velcros are just a big rip-off!",
    "Two wi-fi antennas got married last Saturday. The reception was fantastic!",
    "Two egotists started a fight. It was an I for an I.",
    "I was trying to catch some fog earlier but I mist.",
    "What is the computer’s favorite food? Microchips!",
    "Somebody stole all my lamps. I couldn’t be more delighted!",
    "What should you call an absolutely average potato? A commentator.",
    "How do you make a good egg-roll? You push it down a hill.",
    "The world tongue-twister champion just got arrested. I hear they're gonna give him a really tough sentence.",
    "So what if I don't know what \"Armageddon\" means? It's not the end of the world.",
    "I recently decided to sell my vacuum cleaner since all it was doing was gathering dust.",
    "If i get $0.50 for every failed math exam, I'd have $6.30 now.",
    "My girlfriend and I often laugh about how competative we are. But I laugh more.",
    "Correct punctuation: the difference between a sentence that's well-written and a sentence that's, well, written.",
    "I’d like to start with the chimney jokes – I’ve got a stack of them. The first one is on the house.",
    "The easiest time to add insult to injury is when you’re signing somebody’s cast.",
    "About a week before he died, my uncle had his back covered in lard. After that, he went down hill fast.",
    "I asked my North Korean friend how it was there, he said he couldn't complain.",
    "I threw a boomerang many years ago. I now live in constant fear.",
    "The only dates I get these days are software updates.",
    "The first time I got a universal remote control I thought to myself, \"This changes everything\".",
    "I refused to believe my road worker father was stealing from his job, but when I got home all the signs were there.",
    "Gambling addiction hotlines would do so much better if every fifth caller was a winner.",
    "Just because nobody complains doesn't mean all parachutes are perfect.",
    "To the man on crutches, dressed in camouflage, who stole my wallet - you can hide, but you can't run.",
    "I needed a password eight characters long so I picked Snow White and the Seven Dwarfs."
];

module.exports = defJokes;